// components/TermsAndConditionsAlert.jsx
import {
  AlertDialog,
  AlertDialogTrigger,
  AlertDialogContent,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogDescription,
  AlertDialogCancel,
} from "@/components/ui/alert-dialog";
import { X } from "lucide-react";

export default function TermsAndConditionsAlert() {
  return (
    <AlertDialog>
      <AlertDialogTrigger asChild>
        <button
          type="button"
          className="text-blue-600 underline text-sm hover:text-blue-800 ml-1"
        >
          View T&C
        </button>
      </AlertDialogTrigger>
      <AlertDialogContent className="h-[90vh]">
        <AlertDialogHeader className="text-left">
          <AlertDialogCancel className="absolute top-3 right-3">
            <X />
          </AlertDialogCancel>
          <AlertDialogTitle>Terms & Conditions</AlertDialogTitle>
          <AlertDialogDescription className="max-h-[72vh] overflow-y-auto space-y-4 text-sm leading-relaxed">
            <div className="space-y-6">
              <div>
                <p className="font-medium text-gray-900 mb-2">Introduction</p>
                <p>
                  These terms and conditions ("Seller Terms") govern the sale of items of used school uniforms ("Items") on the electronic platform (the "Platform") operated by Vibrant Venture LLC-FZ (trading under the brand name of Stepup). By giving your items for sale, you agree to comply with these Seller Terms and any other relevant rules or guidelines established by Stepup.
                </p>
              </div>

              <div>
                <p className="font-medium text-gray-900 mb-2">1. Seller Eligibility</p>
                <p>To be eligible to sell second-hand uniforms, you must:</p>
                <ul className="list-disc ml-6 mt-2 space-y-1">
                  <li>be at least 18 years of age.</li>
                  <li>provide accurate information about the Items.</li>
                </ul>
              </div>

              <div>
                <p className="font-medium text-gray-900 mb-2">2. Item Description and Accuracy</p>
                <p className="mb-3">
                  <strong>Condition of Items:</strong> Sellers must provide accurate descriptions of the condition of the Items, including any wear and tear, damage, stains, or defects. The condition of each Item must be clearly indicated as "like new," "gently used," or "worn daily".
                </p>
                <p>
                  <strong>Images:</strong> Sellers must upload clear and accurate photos of the items being sold. Photos must depict the actual item, and images should not be misleading.
                </p>
              </div>

              <div>
                <p className="font-medium text-gray-900 mb-2">3. Pricing and Payment</p>
                <ul className="list-disc ml-6 space-y-2">
                  <li>Stepup will offer a price for your item after an inspection is done by our quality control department. This can take up to five (5) working days.</li>
                  <li>You are required to confirm your acceptance or denial to the price offered for your uniform by Stepup within twenty-four (24) hours of receiving the notification.</li>
                  <li>Payment for Items will be processed through the Platform's payment system or by bank transfer, at the discretion of Stepup. Sellers are solely responsible for ensuring that their payment information is accurate and up-to-date.</li>
                </ul>
              </div>

              <div>
                <p className="font-medium text-gray-900 mb-2">4. Fees</p>
                <p>Stepup does not charge any fee from the Sellers to sell their pre-loved uniforms.</p>
              </div>

              <div>
                <p className="font-medium text-gray-900 mb-2">5. Shipping and Delivery</p>
                <p className="mb-3">
                  <strong>Shipping:</strong> Once the product registration is complete, we will pick up the item/s from your doorstep within two (2) business days.
                </p>
                <p className="mb-3">
                  <strong>Shipping Costs:</strong> We do not charge shipping cost from the Sellers.
                </p>
                <p className="mb-2">
                  <strong>Packaging:</strong>
                </p>
                <ul className="list-disc ml-6 space-y-1">
                  <li>The Seller is responsible for washing the Items and iron/fold it neatly before packing.</li>
                  <li>Sellers must ensure that Items are securely packed to prevent damage during transit.</li>
                  <li>The Seller must ensure that she/he clearly mention the unique code generated by the Platform for the Item being sold, on the packet. If there are multiple Items in one packet, the Seller must mention:
                    <ul className="list-disc ml-6 mt-1 space-y-1">
                      <li>the unique code for each Item on a piece of paper and safely attach it to the Item; and</li>
                      <li>at least one of the unique codes on the outside of the packet.</li>
                    </ul>
                  </li>
                  <li>Stepup shall not be responsible for any loss or damage suffered by the Item during its transit to Stepup.</li>
                </ul>
              </div>

              <div>
                <p className="font-medium text-gray-900 mb-2">6. Returns and Refunds</p>
                <p className="mb-3">
                  <strong>Return Policy:</strong> If the Seller does not agree to sell the Item at the price offered by Stepup, she/he can collect the Item from our office within two (2) business days after receiving the price notification (excluding the day of the notification). Otherwise, the Item will be considered as donation and the Seller shall not have any right to the Item.
                </p>
                <p>
                  <strong>Defective or misrepresented Items:</strong> If the Item received by Stepup is defective, not as described, or damaged, the Seller is obligated to pick up the Item our office within two (2) business days after receiving the rejection notification (excluding the day of the notification). Otherwise, the Item will be considered as donation and the Seller shall not have any right to the Item. Stepup may, at its sole discretion, transfer the defective item to a charity organisation of its choice.
                </p>
              </div>

              <div>
                <p className="font-medium text-gray-900 mb-2">7. Seller Conduct</p>
                <ul className="list-disc ml-6 space-y-1">
                  <li>Sellers must conduct themselves professionally and courteously at all times.</li>
                  <li>Sellers must not engage in deceptive practices, such as misrepresenting the Items for sale or providing false information.</li>
                </ul>
              </div>

              <div>
                <p className="font-medium text-gray-900 mb-2">8. Stepup Rights and Responsibilities</p>
                <ul className="list-disc ml-6 space-y-1">
                  <li>Stepup shall have the right to sell the Item at a price determined at its sole discretion.</li>
                  <li>Stepup may temporarily or permanently suspend a Seller's account on the Platform if these Seller Terms are violated.</li>
                </ul>
              </div>

              <div>
                <p className="font-medium text-gray-900 mb-2">9. No Liability</p>
                <p>Stepup disclaims, to the maximum extent permissible by law, any liability to the Seller or any other party as a result of the use of and/or sale of any Item on the Platform.</p>
              </div>

              <div>
                <p className="font-medium text-gray-900 mb-2">10. Governing Law</p>
                <p>The Seller Terms shall be interpreted in accordance with the provisions of the laws of the United Arab Emirates. The courts in Dubai shall have the jurisdiction over any disputes arising from the use of the Platform.</p>
              </div>

              <div>
                <p className="font-medium text-gray-900 mb-2">11. Modifications to Seller Terms</p>
                <p>Stepup reserves the right to modify these Seller Terms at any time. The Sellers shall be notified about the changes and, by continuing to access or utilise the Platform, the Seller is deemed to have agreed to the updated Seller Terms.</p>
              </div>
            </div>
          </AlertDialogDescription>
        </AlertDialogHeader>
      </AlertDialogContent>
    </AlertDialog>
  );
}